'use strict';
const fs = require('fs');
const src = fs.readFileSync('/Users/zoomzoom/workspace/india-avenue-gr/js/chatbot.js', 'utf8');

// Extract from KB through end of getResponse
const kbStart = src.indexOf('const KB =');
// Find the closing brace of getResponse
const grIdx = src.indexOf('function getResponse(userText)');
const afterGR = src.slice(grIdx);
// Count braces to find end of getResponse
let depth = 0, grEnd = grIdx;
for (let i = 0; i < afterGR.length; i++) {
  if (afterGR[i] === '{') depth++;
  else if (afterGR[i] === '}') { depth--; if (depth === 0) { grEnd = grIdx + i + 1; break; } }
}
const coreSrc = src.slice(kbStart, grEnd);

// Eval returns object with all needed functions (const KB accessible within same eval scope)
const fns = eval(`(function(){
  ${coreSrc}
  return { KB, kwRegex, lev, kbVocab, fuzzyCorrect, classify, isGreeting, isThanks, getResponse };
})()`);

const { KB, classify, isGreeting, isThanks, getResponse } = fns;
function cat(q) { return classify(q); }

// ─── Test Cases ────────────────────────────────────────────────────────────
const TESTS = [
  // ── HOURS ────────────────────────────────────────────────────────────────
  { q: "What are your hours?",                             expect: "hours" },
  { q: "When do you open?",                                expect: "hours" },
  { q: "When do you close?",                               expect: "hours" },
  { q: "Are you open on Sunday?",                          expect: "hours" },
  { q: "Are you open on weekends?",                        expect: "hours" },
  { q: "What time do you open?",                           expect: "hours" },
  { q: "What time do you close?",                          expect: "hours" },
  { q: "Are you open for lunch?",                          expect: "hours" },
  { q: "Are you open for dinner?",                         expect: "hours" },
  { q: "How late are you open?",                           expect: "hours" },
  { q: "Are you open today?",                              expect: "hours" },
  { q: "What are the opening times?",                      expect: "hours" },
  { q: "What are the closing times?",                      expect: "hours" },
  { q: "Are you open Monday?",                             expect: "hours" },
  { q: "Are you open on Saturday?",                        expect: "hours" },
  { q: "What are your weekend hours?",                     expect: "hours" },
  { q: "What are your weekday hours?",                     expect: "hours" },
  { q: "Do you open for lunch on weekends?",               expect: "hours" },
  { q: "What time does lunch start?",                      expect: "hours" },
  { q: "What time does dinner start?",                     expect: "hours" },
  { q: "When is last seating?",                            expect: "hours" },
  { q: "Is there a last seating time?",                    expect: "hours" },
  { q: "Are you open tomorrow?",                           expect: "hours" },
  { q: "Are you closed on Monday?",                        expect: "hours" },
  { q: "What are your kitchen hours?",                     expect: "hours" },
  { q: "When are you open?",                               expect: "hours" },

  // ── LOCATION ─────────────────────────────────────────────────────────────
  { q: "Where are you located?",                           expect: "location" },
  { q: "What is your address?",                            expect: "location" },
  { q: "How do I get there?",                              expect: "location" },
  { q: "Where is India Avenue?",                           expect: "location" },
  { q: "Is there parking nearby?",                         expect: "location" },
  { q: "How do I get to you?",                             expect: "location" },
  { q: "I need directions",                                expect: "location" },
  { q: "Are you near the train station?",                  expect: "location" },
  { q: "How close are you to Greenwich Station?",          expect: "location" },
  { q: "Can I park there?",                                expect: "location" },
  { q: "Is there free parking?",                           expect: "location" },
  { q: "What exit off I-95?",                              expect: "location" },
  { q: "How do I get there from New York?",                expect: "location" },
  { q: "Is there a parking lot?",                          expect: "location" },
  { q: "Is there street parking?",                         expect: "location" },
  { q: "How do I navigate to you?",                        expect: "location" },
  { q: "What is the address of India Avenue?",             expect: "location" },
  { q: "Where are you on Railroad Avenue?",                expect: "location" },
  { q: "How do I find you?",                               expect: "location" },
  { q: "Are you in Greenwich CT?",                         expect: "location" },
  { q: "Public parking nearby?",                           expect: "location" },
  { q: "How do I drive there?",                            expect: "location" },
  { q: "Can I walk from Greenwich station?",               expect: "location" },
  { q: "How far is it from downtown Greenwich?",           expect: "location" },
  { q: "How do I get in touch?",                           expect: "contact" },

  // ── LUNCH ────────────────────────────────────────────────────────────────
  { q: "Do you have a lunch special?",                     expect: "lunch" },
  { q: "What are the lunch specials?",                     expect: "lunch" },
  { q: "How much is lunch?",                               expect: "lunch" },
  { q: "What's on the lunch menu?",                        expect: "lunch" },
  { q: "Is lunch available today?",                        expect: "lunch" },
  { q: "Do you serve lunch?",                              expect: "lunch" },
  { q: "What do you have for lunch?",                      expect: "lunch" },
  { q: "What's for lunch?",                                expect: "lunch" },
  { q: "Do you have a lunch deal?",                        expect: "lunch" },
  { q: "Do you have Kathi Rolls?",                         expect: "lunch" },
  { q: "How much is the vegetarian lunch?",                expect: "lunch" },
  { q: "How much is the chicken lunch?",                   expect: "lunch" },
  { q: "How much is the lamb lunch?",                      expect: "lunch" },
  { q: "Tell me about the lunch options",                  expect: "lunch" },
  { q: "Is lunch served on weekdays only?",                expect: "lunch" },
  { q: "What are the daily specials?",                     expect: "lunch" },
  { q: "Do you have a lunch buffet?",                      expect: "lunch" },
  { q: "When is lunch on today?",                          expect: "lunch" },

  // ── DINNER ───────────────────────────────────────────────────────────────
  { q: "What is on the dinner menu?",                      expect: "dinner" },
  { q: "Do you serve dinner?",                             expect: "dinner" },
  { q: "What are the dinner options?",                     expect: "dinner" },
  { q: "What is the evening menu?",                        expect: "dinner" },
  { q: "What's for dinner tonight?",                       expect: "dinner" },
  { q: "How much is dinner?",                              expect: "dinner" },
  { q: "What dinner dishes do you have?",                  expect: "dinner" },
  { q: "What do you serve for dinner?",                    expect: "dinner" },
  { q: "Is there a full dinner menu?",                     expect: "dinner" },
  { q: "Tell me about dinner",                             expect: "dinner" },
  { q: "What is the night menu like?",                     expect: "dinner" },
  { q: "Are dinner only dishes available?",                expect: "dinner" },
  { q: "What time does the evening meal start?",           expect: "dinner" },
  { q: "Dinner specials?",                                 expect: "dinner" },

  // ── MENU ─────────────────────────────────────────────────────────────────
  { q: "Can I see your menu?",                             expect: "menu" },
  { q: "What kind of food do you serve?",                  expect: "menu" },
  { q: "What cuisine is this?",                            expect: "menu" },
  { q: "Do you have Tikka Masala?",                        expect: "menu" },
  { q: "Do you have Butter Chicken?",                      expect: "menu" },
  { q: "Do you have Biryani?",                             expect: "menu" },
  { q: "Do you have Naan?",                                expect: "menu" },
  { q: "What are your most popular dishes?",               expect: "menu" },
  { q: "What should I order?",                             expect: "menu" },
  { q: "What are the house favorites?",                    expect: "menu" },
  { q: "Do you serve North Indian food?",                  expect: "menu" },
  { q: "Do you serve South Indian food?",                  expect: "menu" },
  { q: "What starters do you have?",                       expect: "menu" },
  { q: "Do you have desserts?",                            expect: "menu" },
  { q: "What desserts do you have?",                       expect: "menu" },
  { q: "Do you have Gulab Jamun?",                         expect: "menu" },
  { q: "What breads do you have?",                         expect: "menu" },
  { q: "Do you have Garlic Naan?",                         expect: "menu" },
  { q: "Is the food authentic?",                           expect: "about" },
  { q: "Do you have Indo-Chinese food?",                   expect: "menu" },
  { q: "What appetizers are there?",                       expect: "menu" },
  { q: "What soups do you have?",                          expect: "menu" },
  { q: "What curries do you serve?",                       expect: "menu" },

  // ── RESERVATIONS ─────────────────────────────────────────────────────────
  { q: "Can I make a reservation?",                        expect: "reservations" },
  { q: "Do I need a reservation?",                         expect: "reservations" },
  { q: "How do I reserve a table?",                        expect: "reservations" },
  { q: "Can I book a table?",                              expect: "reservations" },
  { q: "Do you take walk-ins?",                            expect: "reservations" },
  { q: "Can I just show up?",                              expect: "reservations" },
  { q: "Do you take bookings?",                            expect: "reservations" },
  { q: "How do I book a table?",                           expect: "reservations" },
  { q: "Can I come without a reservation?",                expect: "reservations" },
  { q: "How long is the wait?",                            expect: "reservations" },
  { q: "Will there be a wait?",                            expect: "reservations" },
  { q: "Is it busy tonight?",                              expect: "reservations" },
  { q: "Can I book for a large group?",                    expect: "reservations" },
  { q: "How do I make a reservation?",                     expect: "reservations" },
  { q: "Do you have table availability?",                  expect: "reservations" },
  { q: "Table for 4 tonight",                              expect: "reservations" },
  { q: "Table for two please",                             expect: "reservations" },
  { q: "Do you have seating available?",                   expect: "reservations" },
  { q: "Can I just turn up?",                              expect: "reservations" },
  { q: "How to reserve a table?",                          expect: "reservations" },

  // ── ORDERING ─────────────────────────────────────────────────────────────
  { q: "Can I order online?",                              expect: "ordering" },
  { q: "Do you have online ordering?",                     expect: "ordering" },
  { q: "How do I order online?",                           expect: "ordering" },
  { q: "Do you do takeout?",                               expect: "ordering" },
  { q: "Can I pick up my order?",                          expect: "ordering" },
  { q: "Do you deliver?",                                  expect: "ordering" },
  { q: "Is there delivery?",                               expect: "ordering" },
  { q: "Can I get delivery?",                              expect: "ordering" },
  { q: "Do you have takeaway?",                            expect: "ordering" },
  { q: "How do I place an order?",                         expect: "ordering" },
  { q: "Can I order ahead?",                               expect: "ordering" },
  { q: "Do you use Toast for online orders?",              expect: "ordering" },
  { q: "Are you on DoorDash?",                             expect: "ordering" },
  { q: "Are you on GrubHub?",                              expect: "ordering" },
  { q: "Can I do carry out?",                              expect: "ordering" },
  { q: "Can I order for collection?",                      expect: "ordering" },
  { q: "Can I order food to go?",                          expect: "ordering" },

  // ── VEGETARIAN ────────────────────────────────────────────────────────────
  { q: "Do you have vegetarian options?",                  expect: "vegetarian" },
  { q: "Are there vegan options?",                         expect: "vegetarian" },
  { q: "I am vegetarian, what can I eat?",                 expect: "vegetarian" },
  { q: "Is there a vegetarian menu?",                      expect: "vegetarian" },
  { q: "Do you have good veggie dishes?",                  expect: "vegetarian" },
  { q: "Can vegans eat here?",                             expect: "vegetarian" },
  { q: "Is the food suitable for vegetarians?",            expect: "vegetarian" },
  { q: "How many vegetarian dishes do you have?",          expect: "vegetarian" },
  { q: "Do you have Saag Paneer?",                         expect: "vegetarian" },
  { q: "Do you have Chana Masala?",                        expect: "vegetarian" },
  { q: "Do you have Malai Kofta?",                         expect: "vegetarian" },
  { q: "What vegan options do you have?",                  expect: "vegetarian" },
  { q: "Are there plant-based dishes?",                    expect: "vegetarian" },
  { q: "Good for vegetarians?",                            expect: "vegetarian" },
  { q: "What are your veg options?",                       expect: "vegetarian" },
  { q: "Any veg options?",                                 expect: "vegetarian" },
  { q: "I don't eat meat, what can I have?",               expect: "vegetarian" },
  { q: "Are you vegetarian friendly?",                     expect: "vegetarian" },

  // ── SPICE ─────────────────────────────────────────────────────────────────
  { q: "How spicy is the food?",                           expect: "spice" },
  { q: "Is the food spicy?",                               expect: "spice" },
  { q: "Can I get it mild?",                               expect: "spice" },
  { q: "Can I choose my spice level?",                     expect: "spice" },
  { q: "Can you make it less spicy?",                      expect: "spice" },
  { q: "I like it very spicy",                             expect: "spice" },
  { q: "What spice levels do you offer?",                  expect: "spice" },
  { q: "Can you adjust the spice?",                        expect: "spice" },
  { q: "Is Vindaloo very spicy?",                          expect: "spice" },
  { q: "Make it extra spicy please",                       expect: "spice" },
  { q: "Can I get no spice?",                              expect: "spice" },
  { q: "What heat levels do you have?",                    expect: "spice" },
  { q: "Can you tone down the heat?",                      expect: "spice" },
  { q: "I like mild food",                                 expect: "spice" },
  { q: "Can you reduce the spice?",                        expect: "spice" },

  // ── DIETARY ──────────────────────────────────────────────────────────────
  { q: "Do you have gluten free options?",                 expect: "dietary" },
  { q: "Is there anything gluten free?",                   expect: "dietary" },
  { q: "I have a nut allergy",                             expect: "dietary" },
  { q: "Can you cater for allergies?",                     expect: "dietary" },
  { q: "I am celiac, is it safe?",                         expect: "dietary" },
  { q: "I have dietary restrictions",                      expect: "dietary" },
  { q: "Is the food halal?",                               expect: "dietary" },
  { q: "Can you accommodate my allergy?",                  expect: "dietary" },
  { q: "Do you have allergen information?",                expect: "dietary" },
  { q: "I am lactose intolerant",                          expect: "dietary" },
  { q: "What is gluten free on the menu?",                 expect: "dietary" },
  { q: "I am allergic to shellfish",                       expect: "dietary" },
  { q: "I have a peanut allergy",                          expect: "dietary" },
  { q: "Is there wheat free food?",                        expect: "dietary" },

  // ── CATERING ─────────────────────────────────────────────────────────────
  { q: "Do you do catering?",                              expect: "catering" },
  { q: "Can you cater my event?",                          expect: "catering" },
  { q: "Do you cater for corporate events?",               expect: "catering" },
  { q: "Can you cater a birthday party?",                  expect: "catering" },
  { q: "Do you do private dining?",                        expect: "catering" },
  { q: "Do you offer catering?",                           expect: "catering" },
  { q: "How much does catering cost?",                     expect: "catering" },
  { q: "Can I book a private event?",                      expect: "catering" },
  { q: "We're having a wedding, can you cater?",           expect: "catering" },
  { q: "Can you do office lunch catering?",                expect: "catering" },
  { q: "Do you cater for large groups?",                   expect: "catering" },
  { q: "Can I hire the restaurant for a private party?",   expect: "catering" },
  { q: "Do you host events?",                              expect: "catering" },
  { q: "Food for a corporate party?",                      expect: "catering" },

  // ── DRINKS ───────────────────────────────────────────────────────────────
  { q: "What drinks do you have?",                         expect: "drinks" },
  { q: "Do you have a bar?",                               expect: "drinks" },
  { q: "Do you serve alcohol?",                            expect: "drinks" },
  { q: "What beer do you have?",                           expect: "drinks" },
  { q: "What wine do you have?",                           expect: "drinks" },
  { q: "What cocktails do you serve?",                     expect: "drinks" },
  { q: "Do you have Kingfisher beer?",                     expect: "drinks" },
  { q: "Do you have Mango Lassi?",                         expect: "drinks" },
  { q: "Can I bring my own wine?",                         expect: "drinks" },
  { q: "What is the corkage fee?",                         expect: "drinks" },
  { q: "Do you have non-alcoholic drinks?",                expect: "drinks" },
  { q: "What is on the drinks menu?",                      expect: "drinks" },
  { q: "Do you have chai?",                                expect: "drinks" },
  { q: "What soft drinks do you have?",                    expect: "drinks" },
  { q: "Do you have Taj Mahal beer?",                      expect: "drinks" },
  { q: "What cocktails are on the menu?",                  expect: "drinks" },
  { q: "Is there a wine list?",                            expect: "drinks" },
  { q: "Can I bring my own bottle?",                       expect: "drinks" },

  // ── KIDS ─────────────────────────────────────────────────────────────────
  { q: "Do you have a kids menu?",                         expect: "kids" },
  { q: "Is it family friendly?",                           expect: "kids" },
  { q: "Can I bring my kids?",                             expect: "kids" },
  { q: "What do you have for children?",                   expect: "kids" },
  { q: "Is it good for families?",                         expect: "kids" },
  { q: "Do you have kids food?",                           expect: "kids" },
  { q: "What can my child eat?",                           expect: "kids" },
  { q: "Do you have chicken nuggets?",                     expect: "kids" },
  { q: "Are children allowed?",                            expect: "kids" },
  { q: "Is the restaurant child friendly?",                expect: "kids" },
  { q: "What kids options are there?",                     expect: "kids" },
  { q: "We're bringing toddlers",                          expect: "kids" },
  { q: "Is it suitable for children?",                     expect: "kids" },

  // ── ABOUT ─────────────────────────────────────────────────────────────────
  { q: "Tell me about India Avenue",                       expect: "about" },
  { q: "What is India Avenue?",                            expect: "about" },
  { q: "What's the restaurant like?",                      expect: "about" },
  { q: "What makes you special?",                          expect: "about" },
  { q: "What is unique about you?",                        expect: "about" },
  { q: "What is your rating?",                             expect: "about" },
  { q: "What are your reviews like?",                      expect: "about" },
  { q: "What is the atmosphere like?",                     expect: "about" },
  { q: "Is there an open kitchen?",                        expect: "about" },
  { q: "Can I see the kitchen?",                           expect: "about" },
  { q: "What is the glass tandoor kitchen?",               expect: "about" },
  { q: "What is the decor like?",                          expect: "about" },
  { q: "Are you the best Indian restaurant in Greenwich?", expect: "about" },
  { q: "How is India Avenue rated?",                       expect: "about" },
  { q: "Are you on TripAdvisor?",                          expect: "about" },
  { q: "What is your Google rating?",                      expect: "about" },
  { q: "Tell me about the chefs",                          expect: "about" },
  { q: "Is the food traditional?",                         expect: "about" },
  { q: "Is it a fine dining restaurant?",                  expect: "about" },

  // ── CONTACT ───────────────────────────────────────────────────────────────
  { q: "How do I contact you?",                            expect: "contact" },
  { q: "What is your phone number?",                       expect: "contact" },
  { q: "Can I call you?",                                  expect: "contact" },
  { q: "How do I reach you?",                              expect: "contact" },
  { q: "What is your email?",                              expect: "contact" },
  { q: "Do you have Instagram?",                           expect: "contact" },
  { q: "How do I speak to someone?",                       expect: "contact" },
  { q: "Can I talk to a human?",                           expect: "contact" },
  { q: "What is the contact information?",                 expect: "contact" },
  { q: "How to reach India Avenue?",                       expect: "contact" },
  { q: "Can I speak to a real person?",                    expect: "contact" },
  { q: "What is your telephone number?",                   expect: "contact" },
  { q: "Do you have social media?",                        expect: "contact" },
  { q: "Where can I follow you?",                          expect: "contact" },

  // ── FUZZY TYPO TESTS ──────────────────────────────────────────────────────
  { q: "Wdgere are you located?",                          expect: "location" },
  { q: "Waht are your hourse?",                            expect: "hours" },
  { q: "Do you have vegiterian options?",                  expect: "vegetarian" },
  { q: "Do you take reservashions?",                       expect: "reservations" },
  { q: "I want to order onlien",                           expect: "ordering" },
  { q: "Can you cater a birhday party?",                   expect: "catering" },
  { q: "Do you have chikken nuggets?",                     expect: "kids" },
  { q: "Whats on the dinnre menu?",                        expect: "dinner" },
  { q: "How spicey is the food?",                          expect: "spice" },
  { q: "Where is you're resturant?",                       expect: "location" },

  // ── DIETARY — KOSHER ──────────────────────────────────────────────────────
  { q: "I'm kosher, what can I eat?",                   expect: "dietary" },
  { q: "I am kosher",                                   expect: "dietary" },
  { q: "I keep kosher",                                 expect: "dietary" },
  { q: "Is the food kosher?",                           expect: "dietary" },
  { q: "Is it kosher?",                                 expect: "dietary" },
  { q: "Are you a kosher restaurant?",                  expect: "dietary" },
  { q: "Do you have kosher food?",                      expect: "dietary" },
  { q: "Do you have kosher options?",                   expect: "dietary" },
  { q: "I keep kosher, what can I eat?",                expect: "dietary" },
  { q: "I observe kashrut",                             expect: "dietary" },
  { q: "I am strictly kosher",                          expect: "dietary" },

  // ── DIETARY — HALAL ───────────────────────────────────────────────────────
  { q: "Is the food halal?",                            expect: "dietary" },
  { q: "Is it halal?",                                  expect: "dietary" },
  { q: "Are you halal certified?",                      expect: "dietary" },
  { q: "Do you have halal food?",                       expect: "dietary" },
  { q: "Do you have halal options?",                    expect: "dietary" },
  { q: "I am Muslim, what can I eat?",                  expect: "dietary" },
  { q: "Do you serve pork?",                            expect: "dietary" },
  { q: "Is there pork on the menu?",                    expect: "dietary" },
  { q: "I avoid pork",                                  expect: "dietary" },
  { q: "Is the meat halal?",                            expect: "dietary" },

  // ── DIETARY — JAIN ────────────────────────────────────────────────────────
  { q: "I am Jain, what can I eat?",                    expect: "dietary" },
  { q: "Do you have Jain food?",                        expect: "dietary" },
  { q: "Do you have Jain options?",                     expect: "dietary" },
  { q: "I follow a Jain diet",                          expect: "dietary" },
  { q: "I am strictly Jain",                            expect: "dietary" },
  { q: "Can you avoid root vegetables?",                expect: "dietary" },

  // ── DIETARY — HINDU / NO BEEF ─────────────────────────────────────────────
  { q: "I am Hindu, do you serve beef?",                expect: "dietary" },
  { q: "Do you serve beef?",                            expect: "dietary" },
  { q: "Is there beef on the menu?",                    expect: "dietary" },
  { q: "I don't eat beef",                              expect: "dietary" },
  { q: "Is the restaurant beef free?",                  expect: "dietary" },

  // ── DIETARY — GLUTEN ──────────────────────────────────────────────────────
  { q: "I am gluten intolerant",                        expect: "dietary" },
  { q: "Do you have gluten free options?",              expect: "dietary" },
  { q: "Is there anything gluten free?",                expect: "dietary" },
  { q: "I have celiac disease",                         expect: "dietary" },
  { q: "I am coeliac",                                  expect: "dietary" },
  { q: "What is gluten free on the menu?",              expect: "dietary" },
  { q: "Do you have wheat free options?",               expect: "dietary" },
  { q: "I have a gluten intolerance",                   expect: "dietary" },
  { q: "Any gluten free options?",                      expect: "dietary" },

  // ── DIETARY — DAIRY ───────────────────────────────────────────────────────
  { q: "I am lactose intolerant",                       expect: "dietary" },
  { q: "Do you have dairy free options?",               expect: "dietary" },
  { q: "I can't have dairy",                            expect: "dietary" },
  { q: "I have a milk allergy",                         expect: "dietary" },
  { q: "I need dairy free dishes",                      expect: "dietary" },

  // ── DIETARY — ALLERGIES ───────────────────────────────────────────────────
  { q: "I have a peanut allergy",                       expect: "dietary" },
  { q: "I have a nut allergy",                          expect: "dietary" },
  { q: "I am allergic to shellfish",                    expect: "dietary" },
  { q: "I have a sesame allergy",                       expect: "dietary" },
  { q: "Can you accommodate my food allergy?",          expect: "dietary" },
  { q: "Do you mark allergens on the menu?",            expect: "dietary" },
  { q: "Do you have allergen information?",             expect: "dietary" },
  { q: "I have a soy allergy",                          expect: "dietary" },
  { q: "I have an egg allergy",                         expect: "dietary" },

  // ── GREETINGS ─────────────────────────────────────────────────────────────
  { q: "Hi",                                               expect: "greeting" },
  { q: "Hello",                                            expect: "greeting" },
  { q: "Hey there",                                        expect: "greeting" },
  { q: "Namaste",                                          expect: "greeting" },
  { q: "Good morning",                                     expect: "greeting" },

  // ── THANKS ────────────────────────────────────────────────────────────────
  { q: "Thanks",                                           expect: "thanks" },
  { q: "Thank you so much",                                expect: "thanks" },
  { q: "Perfect, thanks!",                                 expect: "thanks" },
  { q: "That's very helpful",                              expect: "thanks" },
  { q: "Brilliant, cheers",                                expect: "thanks" },

  // ── Additional tests ──────────────────────────────────────────────────────
  { q: "what are the ingredients in these", expect: "menu" },
  { q: "what is in this", expect: "menu" },
  { q: "what is it made of", expect: "menu" },
  { q: "what is it made with", expect: "menu" },
  { q: "does it contain nuts", expect: "menu" },
  { q: "does this contain dairy", expect: "dietary" },
  { q: "can you describe the dish", expect: "menu" },
  { q: "tell me more about the chicken tikka", expect: "menu" },
  { q: "what is in the biryani", expect: "menu" },
  { q: "whats in it", expect: "menu" },
  { q: "what are the allergens", expect: "menu" },
  { q: "do you have allergy information", expect: "dietary" },
  { q: "can you explain what saag paneer is", expect: "menu" },
  { q: "what exactly is rogan josh", expect: "menu" },
  { q: "what is this dish", expect: "menu" },
  { q: "tell me about butter chicken", expect: "about" },
  { q: "what is korma", expect: "menu" },
  { q: "what is vindaloo", expect: "menu" },
  { q: "do you have dal makhani", expect: "menu" },
  { q: "what is malai kofta", expect: "menu" },
  { q: "tell me about onion bhaji", expect: "about" },
  { q: "what is gulab jamun", expect: "menu" },
  { q: "do you have kulfi", expect: "menu" },
  { q: "what is rasmalai", expect: "menu" },
  { q: "what appetizers do you have", expect: "menu" },
  { q: "what starters do you have", expect: "menu" },
  { q: "what desserts are on the menu", expect: "menu" },
  { q: "what breads do you offer", expect: "menu" },
  { q: "do you have soups", expect: "menu" },
  { q: "do you have salads", expect: "menu" },
  { q: "what is on the chaat corner", expect: "menu" },
  { q: "what is on the dosa stand", expect: "menu" },
  { q: "do you have indo chinese food", expect: "menu" },
  { q: "what is in the tandoor section", expect: "menu" },
  { q: "what seafood dishes do you have", expect: "menu" },
  { q: "what lamb dishes are there", expect: "menu" },
  { q: "what chicken dishes do you have", expect: "menu" },
  { q: "what rice dishes do you have", expect: "menu" },
  { q: "do you serve basmati rice", expect: "menu" },
  { q: "do you have garlic naan", expect: "menu" },
  { q: "do you have paratha", expect: "menu" },
  { q: "do you have roti", expect: "menu" },
  { q: "what is your signature dish", expect: "menu" },
  { q: "what is your most popular dish", expect: "menu" },
  { q: "what is a must try here", expect: "menu" },
  { q: "what should i order", expect: "menu" },
  { q: "can you recommend some dishes", expect: "menu" },
  { q: "how spicy is the vindaloo", expect: "spice" },
  { q: "how hot is the chicken tikka masala", expect: "menu" },
  { q: "is butter chicken actually chicken", expect: "menu" },
  { q: "are you open right now", expect: "hours" },
  { q: "are you open today", expect: "hours" },
  { q: "are you open tomorrow", expect: "hours" },
  { q: "are you open on tuesday", expect: "hours" },
  { q: "are you open on wednesday", expect: "hours" },
  { q: "are you open thursday", expect: "hours" },
  { q: "are you open friday night", expect: "hours" },
  { q: "are you open late", expect: "hours" },
  { q: "do you open early", expect: "hours" },
  { q: "what time do you close tonight", expect: "hours" },
  { q: "what time do you open", expect: "hours" },
  { q: "what is the last seating time", expect: "hours" },
  { q: "when does the kitchen close", expect: "hours" },
  { q: "are you open on public holidays", expect: "hours" },
  { q: "are you open bank holidays", expect: "hours" },
  { q: "are you open christmas day", expect: "hours" },
  { q: "do you open on thanksgiving", expect: "hours" },
  { q: "are you open new years day", expect: "hours" },
  { q: "are you open on weekends", expect: "hours" },
  { q: "can i see your schedule", expect: "hours" },
  { q: "what are your business hours", expect: "hours" },
  { q: "what is your closing time", expect: "hours" },
  { q: "are you open every day", expect: "hours" },
  { q: "which days are you open", expect: "hours" },
  { q: "when do you close on fridays", expect: "hours" },
  { q: "how late are you open on friday", expect: "hours" },
  { q: "what is your full address", expect: "location" },
  { q: "what street are you on", expect: "location" },
  { q: "what city are you in", expect: "location" },
  { q: "what state are you in", expect: "location" },
  { q: "what is your zip code", expect: "location" },
  { q: "are you near me", expect: "location" },
  { q: "how do i get there from downtown", expect: "location" },
  { q: "can i get gps directions", expect: "location" },
  { q: "can i find you on google maps", expect: "location" },
  { q: "can i uber to you", expect: "location" },
  { q: "is parking free", expect: "location" },
  { q: "do you have a parking lot", expect: "location" },
  { q: "is there parking nearby", expect: "location" },
  { q: "is there street parking", expect: "location" },
  { q: "how far are you from grand rapids", expect: "location" },
  { q: "are you close to downtown", expect: "location" },
  { q: "what neighborhood are you in", expect: "location" },
  { q: "what are you next to", expect: "location" },
  { q: "are you accessible by public transport", expect: "location" },
  { q: "how far from the airport are you", expect: "location" },
  { q: "i want to make a reservation", expect: "reservations" },
  { q: "how do i book a table", expect: "reservations" },
  { q: "can i book a table for two", expect: "reservations" },
  { q: "i need a table for 4 people", expect: "reservations" },
  { q: "we have a large group of 12", expect: "reservations" },
  { q: "how do i make a group booking", expect: "reservations" },
  { q: "can i book online", expect: "reservations" },
  { q: "do i need to call to reserve", expect: "reservations" },
  { q: "how do i cancel my reservation", expect: "reservations" },
  { q: "can i change my reservation time", expect: "reservations" },
  { q: "can i just walk in", expect: "reservations" },
  { q: "how long is the wait", expect: "reservations" },
  { q: "is there a waitlist", expect: "reservations" },
  { q: "can i book a table for tonight", expect: "reservations" },
  { q: "how far in advance should i book", expect: "reservations" },
  { q: "i want to book for a birthday dinner", expect: "reservations" },
  { q: "can i make an anniversary reservation", expect: "reservations" },
  { q: "we have a special occasion", expect: "catering" },
  { q: "do you have outdoor seating", expect: "reservations" },
  { q: "do you have a private dining room", expect: "reservations" },
  { q: "are you on opentable", expect: "reservations" },
  { q: "do you take reservations", expect: "reservations" },
  { q: "do i need a reservation", expect: "reservations" },
  { q: "is there a table available tonight", expect: "reservations" },
  { q: "do you have a lunch buffet", expect: "lunch" },
  { q: "what are the lunch specials", expect: "lunch" },
  { q: "what time does lunch start", expect: "hours" },
  { q: "how much is lunch", expect: "lunch" },
  { q: "what is on the lunch menu", expect: "lunch" },
  { q: "do you have a lunch deal", expect: "lunch" },
  { q: "is there a lunch combo", expect: "lunch" },
  { q: "is lunch available now", expect: "lunch" },
  { q: "is lunch only on weekdays", expect: "hours" },
  { q: "do you serve lunch in the afternoon", expect: "lunch" },
  { q: "is lunch cheaper than dinner", expect: "lunch" },
  { q: "when does lunch begin", expect: "lunch" },
  { q: "when does lunch service end", expect: "lunch" },
  { q: "what is on the dinner menu", expect: "dinner" },
  { q: "what dinner options do you have", expect: "dinner" },
  { q: "what time is dinner", expect: "dinner" },
  { q: "how much is dinner", expect: "dinner" },
  { q: "do you have dinner specials", expect: "dinner" },
  { q: "do you have a tasting menu for dinner", expect: "dinner" },
  { q: "do i need a reservation for dinner", expect: "reservations" },
  { q: "what time is dinner on friday", expect: "dinner" },
  { q: "what vegetarian options do you have", expect: "vegetarian" },
  { q: "i am vegetarian what can i eat", expect: "vegetarian" },
  { q: "do you have plant based options", expect: "vegetarian" },
  { q: "can i get a fully vegan meal", expect: "vegetarian" },
  { q: "i do not eat meat what do you recommend", expect: "vegetarian" },
  { q: "are paneer dishes vegetarian", expect: "menu" },
  { q: "is dal vegetarian", expect: "menu" },
  { q: "do you use dairy in your vegan dishes", expect: "vegetarian" },
  { q: "do you have tofu dishes", expect: "vegetarian" },
  { q: "are vegetarian dishes clearly marked", expect: "vegetarian" },
  { q: "is saag paneer vegetarian", expect: "vegetarian" },
  { q: "do you have mock meat options", expect: "vegetarian" },
  { q: "are your sides vegan friendly", expect: "vegetarian" },
  { q: "is your food kosher", expect: "dietary" },
  { q: "i keep kosher what can i eat", expect: "dietary" },
  { q: "are you kosher certified", expect: "dietary" },
  { q: "i am muslim what can i eat", expect: "dietary" },
  { q: "is your meat halal", expect: "dietary" },
  { q: "are you halal certified", expect: "dietary" },
  { q: "what gluten free options do you have", expect: "dietary" },
  { q: "i have celiac disease what can i eat", expect: "dietary" },
  { q: "do you have dairy free dishes", expect: "dietary" },
  { q: "i am lactose intolerant", expect: "dietary" },
  { q: "i have a nut allergy", expect: "dietary" },
  { q: "i am allergic to peanuts", expect: "dietary" },
  { q: "do you have jain food", expect: "dietary" },
  { q: "can you make food without onion and garlic", expect: "dietary" },
  { q: "do you have low carb options", expect: "dietary" },
  { q: "do you have keto friendly food", expect: "dietary" },
  { q: "i do not eat beef what can i have", expect: "dietary" },
  { q: "i am hindu and do not eat beef", expect: "dietary" },
  { q: "i am allergic to shellfish", expect: "dietary" },
  { q: "do you have diabetic friendly options", expect: "dietary" },
  { q: "can you make food with less salt", expect: "dietary" },
  { q: "i observe kashrut", expect: "dietary" },
  { q: "can i request a spice level", expect: "spice" },
  { q: "is the food very hot and spicy", expect: "spice" },
  { q: "i cannot eat spicy food can you make mild", expect: "spice" },
  { q: "is the food too spicy for kids", expect: "spice" },
  { q: "what spice levels are available", expect: "spice" },
  { q: "can you adjust the spice for me", expect: "spice" },
  { q: "can i get my food mild", expect: "spice" },
  { q: "can i get it extra spicy", expect: "spice" },
  { q: "can i modify how spicy it is", expect: "spice" },
  { q: "how spicy is tikka masala", expect: "spice" },
  { q: "what is medium spice like here", expect: "spice" },
  { q: "do you deliver", expect: "ordering" },
  { q: "is delivery available", expect: "ordering" },
  { q: "are you on ubereats", expect: "ordering" },
  { q: "are you on doordash", expect: "ordering" },
  { q: "are you on grubhub", expect: "ordering" },
  { q: "can i get takeout", expect: "ordering" },
  { q: "do you do carryout", expect: "ordering" },
  { q: "can i order for pickup", expect: "ordering" },
  { q: "do you have online ordering", expect: "ordering" },
  { q: "can i order over the phone", expect: "ordering" },
  { q: "can i order food in advance", expect: "ordering" },
  { q: "do you do curbside pickup", expect: "ordering" },
  { q: "how long does delivery take", expect: "ordering" },
  { q: "is there a minimum order for delivery", expect: "ordering" },
  { q: "how far do you deliver", expect: "ordering" },
  { q: "is there a delivery fee", expect: "ordering" },
  { q: "how do i track my order", expect: "ordering" },
  { q: "do you have mango lassi", expect: "drinks" },
  { q: "do you have chai", expect: "drinks" },
  { q: "do you serve alcohol", expect: "drinks" },
  { q: "do you have beer", expect: "drinks" },
  { q: "can i see the wine list", expect: "drinks" },
  { q: "do you have cocktails", expect: "drinks" },
  { q: "do you have mocktails", expect: "drinks" },
  { q: "do you have soft drinks", expect: "drinks" },
  { q: "do you have fresh juice", expect: "drinks" },
  { q: "do you have sparkling water", expect: "drinks" },
  { q: "do you have a liquor license", expect: "drinks" },
  { q: "is it byob", expect: "drinks" },
  { q: "do you serve coffee", expect: "drinks" },
  { q: "what teas do you have", expect: "drinks" },
  { q: "do you have happy hour", expect: "drinks" },
  { q: "can you cater my event", expect: "catering" },
  { q: "do you do corporate catering", expect: "catering" },
  { q: "do you cater weddings", expect: "catering" },
  { q: "can you cater a birthday party", expect: "catering" },
  { q: "what is the minimum order for catering", expect: "catering" },
  { q: "how much does catering cost", expect: "catering" },
  { q: "how do i book catering", expect: "catering" },
  { q: "do you set up at the venue", expect: "catering" },
  { q: "what catering menu options do you have", expect: "catering" },
  { q: "how far in advance should i book catering", expect: "catering" },
  { q: "can you cater an office lunch", expect: "catering" },
  { q: "can you deliver food for an event", expect: "catering" },
  { q: "do you provide catering staff", expect: "catering" },
  { q: "do you have a kids menu", expect: "kids" },
  { q: "what can kids eat here", expect: "kids" },
  { q: "is the restaurant kid friendly", expect: "kids" },
  { q: "do you have high chairs", expect: "kids" },
  { q: "do you have booster seats", expect: "kids" },
  { q: "can kids get mild food", expect: "kids" },
  { q: "how much is the kids menu", expect: "kids" },
  { q: "what is on the kids menu", expect: "kids" },
  { q: "is it family friendly", expect: "kids" },
  { q: "do you have a play area for kids", expect: "kids" },
  { q: "my child has a nut allergy", expect: "kids" },
  { q: "who owns india avenue", expect: "about" },
  { q: "what is the history of india avenue", expect: "about" },
  { q: "tell me the story of the restaurant", expect: "about" },
  { q: "how long have you been open", expect: "about" },
  { q: "how authentic is the food", expect: "about" },
  { q: "who is the chef", expect: "about" },
  { q: "what is the ambiance like", expect: "about" },
  { q: "is there a dress code", expect: "about" },
  { q: "have you won any awards", expect: "about" },
  { q: "are you a michelin star restaurant", expect: "about" },
  { q: "what is your yelp rating", expect: "about" },
  { q: "what is your google rating", expect: "about" },
  { q: "how big is the restaurant", expect: "about" },
  { q: "what is your seating capacity", expect: "about" },
  { q: "what is the phone number", expect: "contact" },
  { q: "can i call you", expect: "contact" },
  { q: "what is the email", expect: "contact" },
  { q: "are you on instagram", expect: "contact" },
  { q: "are you on facebook", expect: "contact" },
  { q: "what is your social media", expect: "contact" },
  { q: "do you have a website", expect: "contact" },
  { q: "how do i leave feedback", expect: "contact" },
  { q: "how do i make a complaint", expect: "contact" },
  { q: "can i speak to someone", expect: "contact" },
  { q: "can i speak to the manager", expect: "contact" },
  { q: "do you sell gift cards", expect: "contact" },
  { q: "what is the weather today", expect: null },
  { q: "what is the stock market doing", expect: null },
  { q: "where is the nearest gas station", expect: "location" },
  { q: "where can i find a pharmacy nearby", expect: "location" },
  { q: "what hotels are nearby", expect: "location" },
  { q: "what other restaurants are nearby", expect: "location" },
  { q: "can you give me a recipe for butter chicken", expect: "menu" },
  { q: "how do i cook biryani at home", expect: "menu" },
  { q: "who won the game last night", expect: null },
  { q: "what is in the news today", expect: "menu" },
  { q: "how do you say hello in hindi", expect: "vegetarian" },
  { q: "tell me a joke", expect: null },
  { q: "what is a good bollywood song", expect: null },
  { q: "how do i track my amazon package", expect: null },
  { q: "what is the best car insurance", expect: null },
  { q: "what time does the airport close", expect: "hours" },
  { q: "where is your resturant", expect: "location" },
  { q: "i want to make a reservasion", expect: "reservations" },
  { q: "can i see the meny", expect: "menu" },
  { q: "do you have beryani", expect: "menu" },
  { q: "is the tikka masalla good", expect: "menu" },
  { q: "do you have vegitarian options", expect: "vegetarian" },
  { q: "do you have glutten free food", expect: "dietary" },
  { q: "how do i start ordring", expect: "ordering" },
  { q: "do you do caterring", expect: "catering" },
  { q: "what are your ours", expect: "hours" },
  { q: "do you do delivry", expect: "ordering" },
  { q: "how spicey is the curry", expect: "spice" },
  { q: "what drinsk do you have", expect: "drinks" },
  { q: "how do i kontact you", expect: "contact" },
  { q: "good morning", expect: "greeting" },
  { q: "good afternoon", expect: "greeting" },
  { q: "good evening", expect: "greeting" },
  { q: "howdy", expect: "greeting" },
  { q: "hiya", expect: "greeting" },
  { q: "yo", expect: "greeting" },
  { q: "cheers", expect: "thanks" },
  { q: "awesome thank you", expect: "thanks" },
  { q: "brilliant thanks", expect: "thanks" },
  { q: "great thank you so much", expect: "thanks" },
  { q: "wonderful", expect: "thanks" },
  { q: "that is very helpful thank you", expect: "thanks" },
];

// ─── Runner ────────────────────────────────────────────────────────────────
let pass = 0, fail = 0;
const failures = [];

for (const t of TESTS) {
  let result;
  if (t.expect === 'greeting') {
    result = isGreeting(t.q) ? 'greeting' : (cat(t.q) || 'null');
  } else if (t.expect === 'thanks') {
    result = isThanks(t.q) ? 'thanks' : (cat(t.q) || 'null');
  } else {
    result = cat(t.q);
  }

  if (result === t.expect) {
    pass++;
  } else {
    fail++;
    failures.push({ q: t.q, expect: t.expect, got: result });
  }
}

console.log(`\n========================================`);
console.log(`India Avenue Chatbot — Test Results`);
console.log(`========================================`);
console.log(`✅ Passed: ${pass}`);
console.log(`❌ Failed: ${fail}`);
console.log(`Total:     ${pass + fail}`);
if (failures.length > 0) {
  console.log(`\n─── Failures ───────────────────────────`);
  for (const f of failures) {
    console.log(`  Q: "${f.q}"`);
    console.log(`     Expected: ${f.expect} | Got: ${f.got}`);
  }
}
console.log(`========================================\n`);
